services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ../syncthing/config:/config
      - /mnt/nfs/raid1-camelot:/raid1-camelot
      - /mnt/nfs/raid1-bigc:/raid1-bigc
      - /home/xcvb/main-obs-vault:/main-obs-vault
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    user: "1000:1000"
    restart: unless-stopped
